### ISSUE TITLE
Can't run server on Windows

### ISSUE THREAD

**Issue by gillespieza** [concentricsky/badgr-ui#31]
When I run `npm run server:dev` (or just `npm run server`), I get the following error:
`
λ npm run server:dev

> badgr-ui@2.16.1 server:dev D:\wamp64\www\badgr\badgr-ui
> node $NODE_DEBUG_OPTION node_modules/webpack-dev-server/bin/webpack-dev-server.js --config config/webpack.dev.js --progress --profile --colors --watch --host 0.0.0.0 --content-base src/

module.js:549
    throw err;
    ^

Error: Cannot find module 'D:\wamp64\www\badgr\badgr-ui\$NODE_DEBUG_OPTION'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! badgr-ui@2.16.1 server:dev: `node $NODE_DEBUG_OPTION node_modules/webpack-dev-server/bin/webpack-dev-server.js --config config/webpack.dev.js --progress --profile --colors --watch --host 0.0.0.0 --content-base src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the badgr-ui@2.16.1 server:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Amanda\AppData\Roaming\npm-cache\_logs\2018-10-03T07_43_07_980Z-debug.log
`

**Comment by gillespieza** [comment]
Same error with `npm start`

**Comment by nqthqn** [comment]
Maybe the `NODE_DEBUG_OPTION` environment variable is not being set properly?

This may be a red herring — are you using the WebStorm editor? Is everything up to date? What version of node are you running? 

Maybe consider taking a sledgehammer to it — delete `node_modules/`, reinstall [NodeJS LTS](https://nodejs.org/en/), then re do `npm install` and `npm start`.
